services:
  user-management:
    build:
      context: ./apps/user-management
      dockerfile: ./apps/user-management/Dockerfile
      target: development
    command: pnpm run start:dev user-management
    env_file:
      - ./apps/user-management/.env
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
  auth:
    build:
      context: ./apps/auth
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: pnpm run start:dev auth
    env_file:
      - ./apps/auth/.env
    ports:
      - '3001:3001'
  notifications:
    build:
      context: ./apps/notifications
      dockerfile: ./apps/notifications/Dockerfile
      target: development
    command: pnpm run start:dev notifications
    env_file:
      - ./apps/notifications/.env
  mongo:
    image: mongo
    ports:
      - '27017:27017'
